Improved event scripts
Added trap EXIT to clean up lock files at exit.
Redirecting all commands that can have output to either log or /dev/null.

diff --git a/events/copy b/events/copy
--- a/events/copy
+++ b/events/copy
@@ -19,14 +19,19 @@ if [ -f "$LOCKFILE" ]; then
     echo "Error: Another scanning operation is currently in progress" >> "$INSANED_LOGFILE"
     exit 0
 fi
+# cleanup on exit
+finish() {
+    rm -f "$LOCKFILE" >/dev/null 2>&1
+}
+trap finish EXIT
 touch "$LOCKFILE"
-rm -f "$TMPFILE"
+
+
+rm -f "$TMPFILE" >/dev/null 2>&1
 
 # for Canon LiDE 210
 scanimage --device-name "$1" --format tiff --mode Gray \
     -l 2 -t 0 -x 206 -y 293 --resolution 300 --contrast 18 --brightness 4 --swdespeck=yes --despeck 3 > "$TMPFILE"
 
-tiff2ps -c -w 8.11 -h 11.54 "$TMPFILE" | lpr &
-
-rm -f "$LOCKFILE"
+tiff2ps -c -w 8.11 -h 11.54 "$TMPFILE" | lpr >> "$INSANED_LOGFILE" 2>&1 &
 
diff --git a/events/email b/events/email
--- a/events/email
+++ b/events/email
@@ -13,15 +13,20 @@ if [ -f "$LOCKFILE" ]; then
     echo "Error: Another scanning operation is currently in progress" >> "$INSANED_LOGFILE"
     exit 0
 fi
+# cleanup on exit
+finish() {
+    rm -f "$LOCKFILE" >/dev/null 2>&1
+}
+trap finish EXIT
 touch "$LOCKFILE"
-rm -f "$TMPFILE"
+
+
+rm -f "$TMPFILE" >/dev/null 2>&1
 
 # for Canon LiDE 210
 scanimage --device-name "$1" --format tiff --mode Color --swdeskew=yes --swcrop=yes \
     --resolution 150 --contrast 10 --brightness 5 > "$TMPFILE"
 
-convert "$TMPFILE" -quality 90 "$OUTFILE"
+convert "$TMPFILE" -quality 90 "$OUTFILE" >> "$INSANED_LOGFILE" 2>&1
 thunderbird -compose "attachment='$OUTFILE'"
-
-rm -f "$LOCKFILE"
 
diff --git a/events/extra b/events/extra
--- a/events/extra
+++ b/events/extra
@@ -19,6 +19,11 @@ if [ -f "$LOCKFILE" ]; then
     echo "Error: Another scanning operation is currently in progress" >> "$INSANED_LOGFILE"
     exit 0
 fi
+# cleanup on exit
+finish() {
+    rm -f "$LOCKFILE" >/dev/null 2>&1
+}
+trap finish EXIT
 touch "$LOCKFILE"
 
 
@@ -29,7 +34,4 @@ if [ -f "$MULTIPAGE_LOCK" ]; then
     rm -f "$TMPFILE_PAGE" "$TMPFILE_ALL" >> "$INSANED_LOGFILE" 2>&1
 fi
 
-
-# remove lock file
-rm -f "$LOCKFILE"
 
diff --git a/events/file b/events/file
--- a/events/file
+++ b/events/file
@@ -57,6 +57,11 @@ if [ -f "$LOCKFILE" ]; then
     echo "Error: Another scanning operation is currently in progress" >> "$INSANED_LOGFILE"
     exit 0
 fi
+# cleanup on exit
+finish() {
+    rm -f "$LOCKFILE" >/dev/null 2>&1
+}
+trap finish EXIT
 touch "$LOCKFILE"
 
 
@@ -91,8 +96,4 @@ scanNextPage "$OUTFILE"
 
 # add timestamp to the MULTIPAGE_LOCK file
 date '+%s' >> "$MULTIPAGE_LOCK"
-
-
-# remove lock file
-rm -f "$LOCKFILE"
 
diff --git a/events/scan b/events/scan
--- a/events/scan
+++ b/events/scan
@@ -12,17 +12,23 @@ if [ -f "$LOCKFILE" ]; then
     echo "Error: Another scanning operation is currently in progress" >> "$INSANED_LOGFILE"
     exit 0
 fi
+# cleanup on exit
+finish() {
+    rm -f "$LOCKFILE" >/dev/null 2>&1
+}
+trap finish EXIT
 touch "$LOCKFILE"
-rm -f "$TMPFILE"
+
+
+rm -f "$TMPFILE" >/dev/null 2>&1
 
 # for Canon LiDE 210
 scanimage --device-name "$1" --format tiff --mode Color --swdeskew=yes --swcrop=yes \
     --resolution 300 --contrast 2 --brightness 2 > "$TMPFILE"
 
-convert "$TMPFILE" -quality 85 "$OUTFILE"
+convert "$TMPFILE" -quality 85 "$OUTFILE" >> "$INSANED_LOGFILE" 2>&1
 
-rm -f "$TMPFILE"
-rm -f "$LOCKFILE"
+rm -f "$TMPFILE" >/dev/null 2>&1
 
 if ! ps aux | egrep -q 'gwen[v]iew' ; then
     gwenview "$OUTFILE" &
