Scan to multipage PDF files for Canon LiDE 210
Fixed issue #4 (batch mode) by scanning into multipage PDF document.
- Event 'file' adds one page to the current PDF file.
- Event 'extra' stops multipage scanning.
Improved example event, improved variable usage in shell scripts.

diff --git a/events/example b/events/example
--- a/events/example
+++ b/events/example
@@ -26,11 +26,34 @@
 # touch /etc/insaned/events/copy
 # chmod 755 /etc/insaned/events/copy
 #
-# Insaned passes the device name to the script as the first parameter, in case
-# that you have multiple scanners
+# Insaned passes the device name to event scripts as the first parameter (i.e. "$1"),
+# for the case that you have multiple scanners
 
+# it is always good to use variables to have quick access to varios settings
 TMPFILE="/tmp/scan.tiff"
-LOCKFILE="/tmp/copy.lock"
+# required (see usage below)
+LOCKFILE="/tmp/insaned-scan.lock"
+
+# each event script should start with such check
+# it ensures that only one event script is executed at time, so that they do not disturb each other
+# make sure to remove the lock file at the end of script
+if [ -f "$LOCKFILE" ]; then
+  echo "Error: Another scanning operation is currently in progress"
+  exit 0
+fi
+touch "$LOCKFILE"
+
+# always clean up stale temporary files at the beginning of the script
+rm -f "$TMPFILE"
+
+# 
+# put your custom content here
+#
+
+
+#
+# examples:
+#
 
 # shamelessly stolen from scanbuttond
 #
@@ -39,15 +62,19 @@ LOCKFILE="/tmp/copy.lock"
 # ISO A4 paper size so that the scanned document matches the printer
 # output as closely as possible.
 #
-# if [ -f $LOCKFILE ]; then
-#   echo "Error: Another scanning operation is currently in progress"
-#   exit 0
-# fi
-# touch $LOCKFILE
-# rm -f $TMPFILE
 # scanimage --device-name "$1" --format tiff --mode Gray --quick-format A4 \
 # --resolution 300 --sharpness 0 --brightness -3 \
-# --gamma-correction "High contrast printing" > $TMPFILE
-# tiff2ps -z -w 8.27 -h 11.69 $TMPFILE | lpr
-# rm -f $LOCKFILE
+# --gamma-correction "High contrast printing" > "$TMPFILE"
+# tiff2ps -z -w 8.27 -h 11.69 "$TMPFILE" | lpr
+
+
+# This example starts gwenview if it is not already started
+# 
+# if ! ps aux | /bin/egrep -wq 'gwen[v]iew' ; then
+#     gwenview >/dev/null 2>&1 &
+# fi
+
+
+# each event script should end with removing the lock file
+rm -f "$LOCKFILE"
 
